PREFIX dct: <http://purl.org/dc/terms/>

INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://data.lblod.info/id/representatieveOrganen/5871503aa86b44cd470f97228a2ce413> dct:identifier "0464533790" .
    <http://data.lblod.info/id/representatieveOrganen/e224c637ba8bb0e5dfbb87da225b4652> dct:identifier "0898987189" .
    <http://data.lblod.info/id/representatieveOrganen/6f79a1b89678b85009484da7c4a104bc> dct:identifier "0864330673" .
    <http://data.lblod.info/id/representatieveOrganen/c98e270d84a8455b2f4bf16b915aeff2> dct:identifier "0409771253" .
    <http://data.lblod.info/id/representatieveOrganen/78dcd875a7f2a7d0b5767c9fd8052efa> dct:identifier "0687815914" .
    <http://data.lblod.info/id/representatieveOrganen/2267e8e132b5556bd4d0b454c9383ca0> dct:identifier "0409677223" .
    <http://data.lblod.info/id/representatieveOrganen/859ae3dff21dcfd97e70d180569ebad1> dct:identifier "0413234648" .
    <http://data.lblod.info/id/representatieveOrganen/b4d22cde910a7b58b6e4d9c1d3b15fbb> dct:identifier "0408140861" .
    <http://data.lblod.info/id/representatieveOrganen/2089dc85d4ba48a7f28ee4b521af2b26> dct:identifier "0410195380" .
    <http://data.lblod.info/id/representatieveOrganen/45a0c64b0f2ee4ac0fa8c151e6f2209c> dct:identifier "0408472839" .
    <http://data.lblod.info/id/representatieveOrganen/0ebb44c2ef14d86978ea85e74d128ad1> dct:identifier "0412914944" .
  }
}
