version: '3.4'

services:
  frontend:
    image: lblod/frontend-worship-organizations:latest
    restart: "no"
  identifier:
    restart: "no"
    ports:
      - "80:80"
  dispatcher:
    restart: "no"
    volumes:
      - ./config/dispatcher/dispatcher.ex:/config/dispatcher.ex
  triplestore:
    ports:
      - "8890:8890"
    restart: "no"
  db:
    restart: "no"
  migrations:
    volumes:
      - ./config/dev-migrations:/data/migrations/dev/
    restart: "no"
  resource:
    restart: "no"
  cache:
    restart: "no"
  deltanotifier:
    restart: "no"
  mocklogin:
    image: lblod/mock-login-service:latest
    links:
      - db:database
    restart: "no"
  sink:
    restart: "no"
  login:
    restart: "no"
  accountdetail:
    restart: "no"
  uri-info:
    restart: "no"
  file:
    restart: "no"
  error-report-service:
    restart: "no"
  reasoner:
    restart: "no"
  positions-dispatcher:
    restart: "no"
  worship-services-sensitive-consumer:
    restart: "no"
  update-bestuurseenheid-mock-login:
    restart: "no"
