DELETE {
  GRAPH ?g {
    ?s ?p ?o .
  }
} WHERE {
  GRAPH ?g {
    ?s ?p ?o .
  }

  FILTER(STRSTARTS(STR(?g), "http://mu.semte.ch/graphs/organizations/"))

  FILTER NOT EXISTS {
    GRAPH <http://mu.semte.ch/graphs/ingest> {
      ?s ?p ?o .
    }
  }
}
